name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Lint, build, test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies on frontend
        working-directory: flight-diary/flight-diary-frontend
        run: npm install
      - name: Install dependencies on backend
        working-directory: flight-diary/flight-diary-backend
        run: npm install
      - name: Create build folder
        working-directory: flight-diary/flight-diary-backend
        run: mkdir build
      - name: Build app
        working-directory: flight-diary/flight-diary-backend
        run: npm run build:ui

  tag_release:
    name: Bump version and push tag
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message),','),'#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  deploy_app:
    name: Deploy app
    needs: [tag_release]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message),','),'#skip')}}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - working-directory: flight-diary/flight-diary-backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          details: Deployment successful!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          details: Deployment failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
